/* Two purpose-built views. No mutations to registered individuals or assignments. */
(function(root){
'use strict';
const C=root.SleepCore,D=root.SleepData;
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const short={INGREDIENT_FINDER_S:'食S',INGREDIENT_FINDER_M:'食M',HELPING_SPEED_S:'速S',HELPING_SPEED_M:'速M',HELPING_BONUS:'おボ',INVENTORY_S:'所S',INVENTORY_M:'所M',INVENTORY_L:'所L',BERRY_FINDING_S:'きS'};
const statusName={active:'解放済み',projected:'試算で解放',locked:'未解放'};
const name=p=>p.nickname||C.species(p.species)?.name||p.customName||'未入力';
function portrait(p){const sp=C.species(p.species);return `<span class="portrait" aria-hidden="true">${sp?`<img src="assets/pokemon/${sp.dex}.png" alt="" loading="lazy" width="64" height="64">`:'◇'}</span>`;}
function nature(p,compact=false){const n=C.nature(p.nature);if(!n)return '<span class="mini-nature unknown">性格?</span>';const badges=[['ingredient','食'],['speed','速']].flatMap(([key,label])=>n.positiveModifier===key?[`<span class="up" title="${label==='食'?'食材おてつだい確率':'おてつだいスピード'}アップ">${label}↑</span>`]:n.negativeModifier===key?[`<span class="down" title="${label==='食'?'食材おてつだい確率':'おてつだいスピード'}ダウン">${label}↓</span>`]:[]);return `<span class="mini-nature">${badges.join(' ')||(compact?'':'<span title="食材確率・速度の性格補正なし">食速±</span>')}</span>`;}
function skills(p,mode){return `<div class="mini-skills">${p.subskills.map((id,i)=>{if(id&&!short[id])return '';const status=C.slotStatus(p,C.SKILL_LEVELS[i],mode),label=short[id]||'?';return `<span class="mini-skill ${status}" title="Lv.${C.SKILL_LEVELS[i]} ${esc(C.skill(id)?.name||'未入力')}・${statusName[status]}" aria-label="Lv.${C.SKILL_LEVELS[i]} ${esc(C.skill(id)?.name||'未入力')} ${statusName[status]}">${status==='locked'?'·':status==='projected'?'↗':''}${label}</span>`;}).join('')||'<span class="muted">対象スキルなし</span>'}</div>`;}
function miniSlots(p,mode){return `<span class="mini-slots" aria-label="食材1・2・3枠">${p.slots.map((id,i)=>{const ing=C.ingredient(id),status=C.slotStatus(p,C.ING_LEVELS[i],mode);return `<span class="${status}" title="${i+1}枠目 ${esc(ing?.name||'未入力')}・${statusName[status]}" aria-label="${i+1}枠目 ${esc(ing?.name||'未入力')} ${statusName[status]}">${ing?.icon||'?'}${status==='locked'?'<sup>·</sup>':status==='projected'?'<sup>↗</sup>':''}</span>`;}).join('')}</span>`;}
function slotLetters(p){const sp=C.species(p.species),ids=sp?[...new Set(sp.slots.flat().map(s=>s.id))]:[];return p.slots.map(id=>{const i=ids.indexOf(id);return i>=0&&i<3?'ABC'[i]:'?';});}
function letterSlots(p,mode){return `<strong class="letter-slots" aria-label="食材並び ${slotLetters(p).join('')}">${slotLetters(p).map((letter,i)=>{const status=C.slotStatus(p,C.ING_LEVELS[i],mode);return `<span class="${status}" title="${i+1}枠目・${statusName[status]}">${letter}</span>`;}).join('')}</strong>`;}
function daily(p,mode,energy){const r=C.calc(p,mode,energy);return {result:r,items:r.ok?Object.entries(r.counts).filter(([,v])=>v>0):[]};}
function dailyHTML(p,state){const {result:r,items}=daily(p,state.mode,state.energy);return `<div class="compact-yield" aria-label="1日の食材別推定収集数">${r.ok?items.map(([id,v])=>`<b title="${esc(C.ingredient(id).name)} ${v.toFixed(1)}個 / 24時間">${C.ingredient(id).icon} ${v.toFixed(1)}</b>`).join(''):`<small title="${esc(r.errors.join(' / '))}">— ${r.level>70?'将来・未計算':'条件不足・詳細へ'}</small>`}</div>`;}
function time(seconds){const s=Math.round(seconds);return `${Math.floor(s/3600)}:${String(Math.floor(s%3600/60)).padStart(2,'0')}:${String(s%60).padStart(2,'0')}`;}
function render({state,list,layout,slotsHTML,skillsHTML,levelLabel}){
 const owner=id=>state.pokemon.find(p=>p.id===state.assignments[id]?.pokemonId);
 const people=[...new Map(list.map(i=>owner(i.id)).filter(Boolean).map(p=>[p.id,p])).values()];
 if(layout==='compact')return D.ingredients.map(ing=>{const p=owner(ing.id),a=state.assignments[ing.id],match=list.some(i=>i.id===ing.id);return `<article class="harvest-tile ${match?'':'search-muted'} ${a?.complete?'is-complete':''}" aria-label="${esc(ing.name)}の担当"><button class="ingredient-marker" data-assign="${ing.id}" title="${esc(ing.name)}の担当・厳選状況を編集" aria-label="${esc(ing.name)}の担当・厳選状況を編集">${ing.icon}<small>${a?.complete?'✓':p?'○':'＋'}</small></button>${p?`<div class="compact-top">${dailyHTML(p,state)}</div><div class="compact-row compact-identity"><span class="compact-name-nature"><button class="mini-person" data-detail="${esc(p.id)}" title="Lv.${C.effectiveLevel(p,state.mode)}・詳細を開く"><span class="mini-person-name">${esc(name(p))}</span></button>${nature(p,true)}</span>${letterSlots(p,state.mode)}</div>${skills(p,state.mode)}`:'<div class="empty-owner" aria-label="担当未登録"></div>'}</article>`;}).join('');

 return people.map(p=>{const r=C.calc(p,state.mode,state.energy),assignments=D.ingredients.filter(i=>state.assignments[i.id]?.pokemonId===p.id);return `<article class="compare-card"><header>${portrait(p)}<div><button class="text-button" data-detail="${esc(p.id)}"><h3>${esc(name(p))}</h3></button><div class="compare-species">${esc(C.species(p.species)?.name||p.customName)}</div><div class="compare-level">${levelLabel(p)}</div></div></header><div class="compare-assignments">${assignments.map(i=>`<button data-assign="${i.id}" title="${esc(i.name)}の担当を編集">${i.icon} ${esc(i.name)} <span>${state.assignments[i.id].complete?'✓':'○'}</span></button>`).join('')}</div>${slotsHTML(p)}<div class="compare-nature">${nature(p)}<span>${esc(C.nature(p.nature)?.name||'性格未入力')}</span></div>${skillsHTML(p,true)}<dl class="help-stats"><div><dt>おてつだい時間 <small>げんき0基準</small></dt><dd>${r.ok?time(r.baseInterval):'—'}</dd></div><div><dt>条件下の間隔 <small>げんき${state.energy}一定</small></dt><dd>${r.ok?time(r.interval):'—'}</dd></div></dl><div class="daily-yield"><span>食材別 / 24時間</span>${r.ok?Object.entries(r.counts).filter(([,v])=>v>0).map(([id,v])=>`<b title="${esc(C.ingredient(id).name)}">${C.ingredient(id).icon} ${v.toFixed(1)}<small>個</small></b>`).join(''):`<p>${esc(r.errors[0])}</p>`}</div><button class="button wide" data-detail="${esc(p.id)}">詳細・編集</button></article>`;}).join('')+(list.some(i=>!owner(i.id))?`<div class="unassigned-summary">${list.filter(i=>!owner(i.id)).length}食材は担当未登録です。省スペース表示から担当を設定できます。</div>`:'')||'<div class="empty-message">条件に合う担当個体がありません。</div>';
}
root.BoardView={render,time,nature,skills,miniSlots,slotLetters,letterSlots,daily};
})(globalThis);
