const vm=require('node:vm'),fs=require('node:fs'),assert=require('node:assert/strict'),path=require('node:path');
const ctx={};vm.createContext(ctx);for(const file of ['data.js','core.js','board.js'])vm.runInContext(fs.readFileSync(path.join(__dirname,'..',file),'utf8'),ctx);
const C=ctx.SleepCore,D=ctx.SleepData,B=ctx.BoardView,s=C.emptyState();
const p={id:'test',species:'CHARIZARD',customName:'',nickname:'<script>test</script>',memo:'',level:60,slots:['Sausage','Ginger','Herb'],subskills:['INGREDIENT_FINDER_S','HELPING_SPEED_M','INGREDIENT_FINDER_M','HELPING_BONUS','INVENTORY_L'],nature:'QUIET',ribbon:0,carry:null,mainSkillLevel:null};
s.pokemon=[p];s.assignments.Sausage={pokemonId:p.id,complete:true,note:'',completedAt:null};s.assignments.Ginger={pokemonId:p.id,complete:false,note:'',completedAt:null};
const options={state:s,list:D.ingredients,slotsHTML:()=>'',skillsHTML:()=>'',levelLabel:()=>''};
const before=JSON.stringify(s),compact=B.render({...options,layout:'compact'}),rich=B.render({...options,layout:'rich'});
assert.equal((compact.match(/<article/g)||[]).length,19);assert.equal((rich.match(/<article/g)||[]).length,1);assert.equal(JSON.stringify(s),before);assert(!compact.includes('<script>'));assert(compact.includes('&lt;script&gt;'));
assert(B.nature(p).includes('食↑'));p.nature='BRAVE';assert(B.nature(p).includes('速↑'));
assert(B.skills(p,'current').includes('·おボ'));assert(B.skills(p,'70').includes('↗おボ'));assert(B.skills(p,'80').includes('↗所L'));
assert.equal(B.time(3661),'1:01:01');console.log('PASS 19 tiles, unique individuals, no data mutation, escaped labels, nature directions, unlock states, time formatting');
const current=B.render({...options,layout:'compact'});assert(!current.includes('<img'));assert(!current.includes('portrait'));assert(current.includes('Lv.60'));assert(current.includes('1日'));assert(current.includes(C.calc(p,'current',100).counts.Sausage.toFixed(1)));const duplicate={...p,nature:'BASHFUL',slots:['Sausage','Sausage','Sausage']};const yieldData=B.daily(duplicate,'current',100);assert.equal(yieldData.items.length,1);assert.equal(yieldData.items[0][1],C.calc(duplicate,'current',100).counts.Sausage);assert.equal(B.daily(p,'80',100).items.length,0);assert(!B.nature({...p,nature:'BASHFUL'},true).includes('食速±'));console.log('PASS text-only compact view, level, daily counts, duplicate ingredient totals, future unknown, nature abbreviations');
const visible=compact.replace(/<[^>]*>/g,'');
for(const ing of D.ingredients)assert(!visible.includes(ing.name),'ingredient names must remain in accessible labels only');
assert.equal((compact.match(/class="compact-row compact-heading"/g)||[]).length,19);
assert.equal((compact.match(/class="compact-row compact-traits"/g)||[]).length,2);
assert.equal((compact.match(/class="compact-yield"/g)||[]).length,2);
assert(!visible.includes('1日'));assert(!visible.includes('Lv.60'));
console.log('PASS compact row structure, icon-only ingredients, no redundant daily or level labels');
for(const [slots,expected] of [[['Sausage','Sausage','Sausage'],'AAA'],[['Sausage','Sausage','Ginger'],'AAB'],[['Sausage','Ginger','Sausage'],'ABA'],[['Sausage','Sausage','Herb'],'AAC'],[['Sausage','','Herb'],'A?C']])assert.equal(B.slotLetters({...p,slots}).join(''),expected);
assert.equal(B.slotLetters({...p,species:''}).join(''),'???');
assert(B.render({...options,layout:'compact'}).includes('letter-slots'));
console.log('PASS species-based letters including AAC, missing slots and unknown species');
